# Generated by Django 2.2.3 on 2019-07-26 00:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('name', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('date_register', models.DateField()),
            ],
            options={
                'db_table': 'club',
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('phone', models.CharField(max_length=15)),
                ('gender', models.CharField(choices=[('pria', 'Pria'), ('wanita', 'Wanita')], max_length=10)),
                ('born_place', models.CharField(blank=True, max_length=45, null=True)),
                ('born_date', models.DateField(blank=True, null=True)),
                ('address', models.TextField()),
                ('body_height', models.CharField(blank=True, max_length=25, null=True)),
                ('body_weight', models.CharField(blank=True, max_length=25, null=True)),
                ('draw_length', models.IntegerField(blank=True, default=0, null=True)),
                ('lead', models.BooleanField(default=False)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photo/%Y/%m/%d')),
                ('club', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='member_set', to='organization.Club')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='member', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'member',
                'ordering': ['created'],
            },
        ),
    ]
