# Generated by Django 2.2.3 on 2019-07-30 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_auto_20190731_0324'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logo/%Y/%m/%d'),
        ),
    ]
