# Generated by Django 2.2.3 on 2019-09-26 18:06

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_club_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='club',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='organization.Club'),
        ),
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, default=None, null=True)),
                ('pic', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='division_pic', to='organization.Member')),
            ],
            options={
                'db_table': 'division',
            },
        ),
        migrations.AddField(
            model_name='member',
            name='division',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='organization.Division'),
        ),
    ]
