# Generated by Django 2.2.3 on 2019-09-26 18:06

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0004_auto_20190927_0206'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArcheryRange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('latitude', models.FloatField(default=0)),
                ('longitude', models.FloatField(default=0)),
                ('pic_type', models.CharField(choices=[('personal', 'Personal'), ('club', 'Club'), ('dpc', 'DPC')], max_length=25)),
                ('paid_status', models.BooleanField(default=False)),
                ('paid_amount', models.DecimalField(blank=True, decimal_places=25, default=0, max_digits=50, null=True)),
                ('pic_club', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archery_range', to='organization.Club')),
                ('pic_personal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archery_range', to='organization.Member')),
            ],
            options={
                'db_table': 'archery_range',
            },
        ),
    ]
